const express = require("express");
const multer = require("multer");
const { env } = require("../config/env");
const { requireAuth, resolveActiveCompany, resolveActiveFiscalYear, requireRoles } = require("../middleware/auth");
const { requireCompletedOnboarding } = require("../middleware/onboarding");
const { validate } = require("../middleware/validate");
const { getContacts, getContact, postContact, patchContact, archiveContactRecord, restoreContactRecord } = require("../controllers/contactController");
const { validateCreateContact, validateUpdateContact, validateUnit, validateCategory, validateTaxRate, validatePaymentTerm, validateContactGroup, validateWarehouse, validatePriceList, validateProduct, validateCatalogUpdate } = require("../validators/businessMasterValidators");
const catalogController = require("../controllers/catalogController");
const { postAttachmentUpload, getAttachments, deleteAttachment, getAttachmentDownload } = require("../controllers/attachmentController");

const allowedAttachmentTypes = new Set(["image/jpeg", "image/png", "image/webp", "application/pdf"]);
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: env.uploadMaxBytes, files: 1 }, fileFilter: (_request, file, callback) => callback(null, allowedAttachmentTypes.has(file.mimetype)) });

const businessMasterRouter = express.Router();
businessMasterRouter.use(requireAuth, resolveActiveCompany, resolveActiveFiscalYear, requireCompletedOnboarding);

businessMasterRouter.get("/contacts", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES", "STAFF"), getContacts);
businessMasterRouter.get("/contacts/:id", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES", "STAFF"), getContact);
businessMasterRouter.post("/contacts", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES"), validate(validateCreateContact), postContact);
businessMasterRouter.patch("/contacts/:id", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES"), validate(validateUpdateContact), patchContact);
businessMasterRouter.delete("/contacts/:id", requireRoles("OWNER", "ADMIN", "ACCOUNTANT"), archiveContactRecord);
businessMasterRouter.post("/contacts/:id/restore", requireRoles("OWNER", "ADMIN", "ACCOUNTANT"), restoreContactRecord);
businessMasterRouter.get("/units", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "INVENTORY_MANAGER", "STAFF"), catalogController.getUnits);
businessMasterRouter.post("/units", requireRoles("OWNER", "ADMIN", "INVENTORY_MANAGER"), validate(validateUnit), catalogController.postUnit);
businessMasterRouter.get("/units/:id", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "INVENTORY_MANAGER", "STAFF"), catalogController.getUnit);
businessMasterRouter.patch("/units/:id", requireRoles("OWNER", "ADMIN", "INVENTORY_MANAGER"), validate(validateCatalogUpdate("units")), catalogController.patchUnit);
businessMasterRouter.delete("/units/:id", requireRoles("OWNER", "ADMIN", "INVENTORY_MANAGER"), catalogController.archiveUnit);
businessMasterRouter.post("/units/:id/restore", requireRoles("OWNER", "ADMIN", "INVENTORY_MANAGER"), catalogController.restoreUnit);
businessMasterRouter.get("/categories", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "INVENTORY_MANAGER", "STAFF"), catalogController.getCategories);
businessMasterRouter.post("/categories", requireRoles("OWNER", "ADMIN", "INVENTORY_MANAGER"), validate(validateCategory), catalogController.postCategory);
businessMasterRouter.get("/categories/:id", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "INVENTORY_MANAGER", "STAFF"), catalogController.getCategory);
businessMasterRouter.patch("/categories/:id", requireRoles("OWNER", "ADMIN", "INVENTORY_MANAGER"), validate(validateCatalogUpdate("categories")), catalogController.patchCategory);
businessMasterRouter.delete("/categories/:id", requireRoles("OWNER", "ADMIN", "INVENTORY_MANAGER"), catalogController.archiveCategory);
businessMasterRouter.post("/categories/:id/restore", requireRoles("OWNER", "ADMIN", "INVENTORY_MANAGER"), catalogController.restoreCategory);
businessMasterRouter.get("/tax-rates", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "STAFF"), catalogController.getTaxRates);
businessMasterRouter.post("/tax-rates", requireRoles("OWNER", "ADMIN", "ACCOUNTANT"), validate(validateTaxRate), catalogController.postTaxRate);
businessMasterRouter.get("/tax-rates/:id", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "STAFF"), catalogController.getTaxRate);
businessMasterRouter.patch("/tax-rates/:id", requireRoles("OWNER", "ADMIN", "ACCOUNTANT"), validate(validateCatalogUpdate("tax-rates")), catalogController.patchTaxRate);
businessMasterRouter.delete("/tax-rates/:id", requireRoles("OWNER", "ADMIN", "ACCOUNTANT"), catalogController.archiveTaxRate);
businessMasterRouter.post("/tax-rates/:id/restore", requireRoles("OWNER", "ADMIN", "ACCOUNTANT"), catalogController.restoreTaxRate);
businessMasterRouter.get("/payment-terms", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES", "STAFF"), catalogController.getPaymentTerms);
businessMasterRouter.post("/payment-terms", requireRoles("OWNER", "ADMIN", "ACCOUNTANT"), validate(validatePaymentTerm), catalogController.postPaymentTerm);
businessMasterRouter.get("/payment-terms/:id", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES", "STAFF"), catalogController.getPaymentTerm);
businessMasterRouter.patch("/payment-terms/:id", requireRoles("OWNER", "ADMIN", "ACCOUNTANT"), validate(validateCatalogUpdate("payment-terms")), catalogController.patchPaymentTerm);
businessMasterRouter.delete("/payment-terms/:id", requireRoles("OWNER", "ADMIN", "ACCOUNTANT"), catalogController.archivePaymentTerm);
businessMasterRouter.post("/payment-terms/:id/restore", requireRoles("OWNER", "ADMIN", "ACCOUNTANT"), catalogController.restorePaymentTerm);
businessMasterRouter.get("/contact-groups", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES", "STAFF"), catalogController.getContactGroups);
businessMasterRouter.post("/contact-groups", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES"), validate(validateContactGroup), catalogController.postContactGroup);
businessMasterRouter.get("/contact-groups/:id", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES", "STAFF"), catalogController.getContactGroup);
businessMasterRouter.patch("/contact-groups/:id", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES"), validate(validateCatalogUpdate("contact-groups")), catalogController.patchContactGroup);
businessMasterRouter.delete("/contact-groups/:id", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES"), catalogController.archiveContactGroup);
businessMasterRouter.post("/contact-groups/:id/restore", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES"), catalogController.restoreContactGroup);
businessMasterRouter.get("/warehouses", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "INVENTORY_MANAGER", "STAFF"), catalogController.getWarehouses);
businessMasterRouter.post("/warehouses", requireRoles("OWNER", "ADMIN", "INVENTORY_MANAGER"), validate(validateWarehouse), catalogController.postWarehouse);
businessMasterRouter.get("/warehouses/:id", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "INVENTORY_MANAGER", "STAFF"), catalogController.getWarehouse);
businessMasterRouter.patch("/warehouses/:id", requireRoles("OWNER", "ADMIN", "INVENTORY_MANAGER"), validate(validateCatalogUpdate("warehouses")), catalogController.patchWarehouse);
businessMasterRouter.delete("/warehouses/:id", requireRoles("OWNER", "ADMIN", "INVENTORY_MANAGER"), catalogController.archiveWarehouse);
businessMasterRouter.post("/warehouses/:id/restore", requireRoles("OWNER", "ADMIN", "INVENTORY_MANAGER"), catalogController.restoreWarehouse);
businessMasterRouter.get("/price-lists", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES", "STAFF"), catalogController.getPriceLists);
businessMasterRouter.post("/price-lists", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES"), validate(validatePriceList), catalogController.postPriceList);
businessMasterRouter.get("/price-lists/:id", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES", "STAFF"), catalogController.getPriceList);
businessMasterRouter.patch("/price-lists/:id", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES"), validate(validateCatalogUpdate("price-lists")), catalogController.patchPriceList);
businessMasterRouter.delete("/price-lists/:id", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES"), catalogController.archivePriceList);
businessMasterRouter.post("/price-lists/:id/restore", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES"), catalogController.restorePriceList);
businessMasterRouter.get("/attachments", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES", "STAFF"), getAttachments);
businessMasterRouter.post("/attachments", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES"), upload.single("file"), postAttachmentUpload);
businessMasterRouter.get("/attachments/:id/download", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES", "STAFF"), getAttachmentDownload);
businessMasterRouter.delete("/attachments/:id", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES"), deleteAttachment);
businessMasterRouter.get("/products", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES", "INVENTORY_MANAGER", "STAFF"), catalogController.getProducts);
businessMasterRouter.post("/products", requireRoles("OWNER", "ADMIN", "INVENTORY_MANAGER"), validate(validateProduct), catalogController.postProduct);
businessMasterRouter.get("/products/:id", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES", "INVENTORY_MANAGER", "STAFF"), catalogController.getProduct);
businessMasterRouter.patch("/products/:id", requireRoles("OWNER", "ADMIN", "INVENTORY_MANAGER"), validate(validateCatalogUpdate("products")), catalogController.patchProduct);
businessMasterRouter.delete("/products/:id", requireRoles("OWNER", "ADMIN", "INVENTORY_MANAGER"), catalogController.archiveProduct);
businessMasterRouter.post("/products/:id/restore", requireRoles("OWNER", "ADMIN", "INVENTORY_MANAGER"), catalogController.restoreProduct);

module.exports = { businessMasterRouter };
