const express = require("express");
const { requireAuth, resolveActiveCompany, resolveActiveFiscalYear, requireRoles } = require("../middleware/auth");
const { requireCompletedOnboarding } = require("../middleware/onboarding");
const { validate } = require("../middleware/validate");
const { validatePan, validateVat } = require("../validators/localizationValidators");
const controller = require("../controllers/localizationController");
const localizationRouter = express.Router();
localizationRouter.use(requireAuth, resolveActiveCompany, resolveActiveFiscalYear, requireCompletedOnboarding);
localizationRouter.get("/pan", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "STAFF"), controller.getPan);
localizationRouter.patch("/pan", requireRoles("OWNER", "ADMIN"), validate(validatePan), controller.patchPan);
localizationRouter.get("/vat", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "STAFF"), controller.getVat);
localizationRouter.patch("/vat", requireRoles("OWNER", "ADMIN"), validate(validateVat), controller.patchVat);
localizationRouter.get("/vat/calculate", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES"), controller.calculateVat);
localizationRouter.get("/calendar/ad-to-bs", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES", "STAFF"), controller.adToBs);
localizationRouter.get("/calendar/bs-to-ad", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES", "STAFF"), controller.bsToAd);
localizationRouter.get("/calendar/today", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES", "STAFF"), controller.todayBs);
localizationRouter.get("/calendar/month-name", requireRoles("OWNER", "ADMIN", "ACCOUNTANT", "SALES", "STAFF"), controller.getBsMonthName);
localizationRouter.post("/fiscal-years/:id/close", requireRoles("OWNER", "ADMIN"), controller.closeFiscalYear);
module.exports = { localizationRouter };
