const branchService = require("../services/branchService");
const { asyncHandler } = require("../utils/asyncHandler");
const { sendSuccess } = require("../utils/apiResponse");
const getBranches = asyncHandler(async (request, response) => sendSuccess(response, 200, "Branches fetched successfully.", await branchService.listBranches(request.auth.activeCompanyId)));
const postBranch = asyncHandler(async (request, response) => sendSuccess(response, 201, "Branch created successfully.", await branchService.createBranch(request.auth.activeCompanyId, request.auth.user._id, request.body)));
const patchBranch = asyncHandler(async (request, response) => sendSuccess(response, 200, "Branch updated successfully.", await branchService.updateBranch(request.auth.activeCompanyId, request.auth.user._id, request.params.id, request.body)));
const deleteBranch = asyncHandler(async (request, response) => { await branchService.archiveBranch(request.auth.activeCompanyId, request.auth.user._id, request.params.id); return response.status(204).end(); });
const getWarehouses = asyncHandler(async (request, response) => sendSuccess(response, 200, "Warehouses fetched successfully.", await branchService.listWarehouses(request.auth.activeCompanyId, request.query)));
const postWarehouse = asyncHandler(async (request, response) => sendSuccess(response, 201, "Warehouse created successfully.", await branchService.createWarehouse(request.auth.activeCompanyId, request.auth.user._id, request.body)));
const patchWarehouse = asyncHandler(async (request, response) => sendSuccess(response, 200, "Warehouse updated successfully.", await branchService.updateWarehouse(request.auth.activeCompanyId, request.auth.user._id, request.params.id, request.body)));
const deleteWarehouse = asyncHandler(async (request, response) => { await branchService.archiveWarehouse(request.auth.activeCompanyId, request.auth.user._id, request.params.id); return response.status(204).end(); });
const restoreWarehouse = asyncHandler(async (request, response) => sendSuccess(response, 200, "Warehouse restored successfully.", await branchService.restoreWarehouse(request.auth.activeCompanyId, request.auth.user._id, request.params.id)));
module.exports = { getBranches, postBranch, patchBranch, deleteBranch, getWarehouses, postWarehouse, patchWarehouse, deleteWarehouse, restoreWarehouse };
