const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  FISCAL_YEAR_LOCKED: "FISCAL_YEAR_LOCKED",
  INVALID_TOKEN: "INVALID_TOKEN",
  ONBOARDING_REQUIRED: "ONBOARDING_REQUIRED"
});

module.exports = {
  ERROR_CODES
};
