const { Branch } = require("../models/Branch");
const { Warehouse } = require("../models/Warehouse");
const { ApiError } = require("../utils/apiError");

function map(model) { return { id: model._id, companyId: model.companyId, branchId: model.branchId, branchCode: model.branchCode, warehouseCode: model.warehouseCode, name: model.name, address: model.address, phone: model.phone, email: model.email, managerId: model.managerId, description: model.description, isDefault: model.isDefault, isActive: model.isActive, createdAt: model.createdAt, updatedAt: model.updatedAt }; }
async function listBranches(companyId) { return (await Branch.find({ companyId, isActive: true }).sort({ name: 1 }).lean()).map(map); }
async function createBranch(companyId, actorUserId, payload) { const count = await Branch.countDocuments({ companyId, isActive: true }); if (payload.isDefault) await Branch.updateMany({ companyId }, { $set: { isDefault: false } }); const branch = await Branch.create({ companyId, branchCode: payload.branchCode.trim().toUpperCase(), name: payload.name.trim(), address: payload.address?.trim() || null, phone: payload.phone?.trim() || null, email: payload.email?.trim().toLowerCase() || null, managerId: payload.managerId || null, isDefault: payload.isDefault === true || count === 0, createdBy: actorUserId, updatedBy: actorUserId }); return map(branch); }
async function listWarehouses(companyId, branchId) { const filters = { companyId, isActive: true }; if (branchId) filters.branchId = branchId; return (await Warehouse.find(filters).sort({ name: 1 }).lean()).map(map); }
async function createWarehouse(companyId, actorUserId, payload) { const branch = await Branch.findOne({ _id: payload.branchId, companyId, isActive: true }).lean(); if (!branch) throw new ApiError(400, "A valid active branch is required."); const count = await Warehouse.countDocuments({ companyId, branchId: branch._id, isActive: true }); if (payload.isDefault) await Warehouse.updateMany({ companyId, branchId: branch._id }, { $set: { isDefault: false } }); const warehouse = await Warehouse.create({ companyId, branchId: branch._id, warehouseCode: payload.warehouseCode.trim().toUpperCase(), name: payload.name.trim(), address: payload.address?.trim() || null, description: payload.description?.trim() || null, isDefault: payload.isDefault === true || count === 0, createdBy: actorUserId, updatedBy: actorUserId }); return map(warehouse); }
async function initializeDefaultBranch(company, userId) { await Branch.updateOne({ companyId: company._id, branchCode: "MAIN" }, { $setOnInsert: { companyId: company._id, branchCode: "MAIN", name: "Main Branch", isDefault: true, isActive: true, createdBy: userId, updatedBy: userId } }, { upsert: true }); }
async function resolveDefaultBranch(companyId) { let branch = await Branch.findOne({ companyId, isDefault: true, isActive: true }).lean(); if (!branch) { await Branch.updateOne({ companyId, branchCode: "MAIN" }, { $setOnInsert: { companyId, branchCode: "MAIN", name: "Main Branch", isDefault: true, isActive: true } }, { upsert: true }); branch = await Branch.findOne({ companyId, branchCode: "MAIN", isActive: true }).lean(); } return branch; }
module.exports = { listBranches, createBranch, listWarehouses, createWarehouse, initializeDefaultBranch, resolveDefaultBranch };
