const { Unit } = require("../models/Unit"); const { ProductCategory } = require("../models/ProductCategory"); const { TaxRate } = require("../models/TaxRate"); const { PaymentTerm } = require("../models/PaymentTerm"); const { Product } = require("../models/Product"); const { ContactGroup } = require("../models/ContactGroup"); const { Warehouse } = require("../models/Warehouse"); const { PriceList } = require("../models/PriceList"); const { Attachment } = require("../models/Attachment"); const { ApiError } = require("../utils/apiError");
const config = { units: { Model: Unit }, categories: { Model: ProductCategory }, "tax-rates": { Model: TaxRate }, "payment-terms": { Model: PaymentTerm }, "contact-groups": { Model: ContactGroup }, warehouses: { Model: Warehouse }, "price-lists": { Model: PriceList }, attachments: { Model: Attachment } };
function map(item) { const value = item.toObject ? item.toObject() : item; return { ...value, id: value._id, _id: undefined }; }
async function list(resource, companyId) { const { Model } = config[resource]; return (await Model.find({ companyId, isActive: true }).sort({ name: 1 }).lean()).map(map); }
async function create(resource, companyId, actorUserId, payload) { const { Model } = config[resource]; const item = await Model.create({ ...payload, companyId, createdBy: actorUserId, updatedBy: actorUserId }); return map(item); }
async function update(resource, companyId, actorUserId, id, payload) { const { Model } = config[resource]; const item = await Model.findOne({ _id: id, companyId }); if (!item) throw new ApiError(404, "Master record was not found."); Object.assign(item, payload, { updatedBy: actorUserId }); await item.save(); return map(item); }
async function archive(resource, companyId, actorUserId, id) { const { Model } = config[resource]; const item = await Model.findOne({ _id: id, companyId }); if (!item) throw new ApiError(404, "Master record was not found."); Object.assign(item, { isActive: false, deletedAt: new Date(), deletedBy: actorUserId, updatedBy: actorUserId }); await item.save(); return map(item); }
async function restore(resource, companyId, actorUserId, id) { const { Model } = config[resource]; const item = await Model.findOne({ _id: id, companyId }); if (!item) throw new ApiError(404, "Master record was not found."); Object.assign(item, { isActive: true, deletedAt: null, deletedBy: null, updatedBy: actorUserId }); await item.save(); return map(item); }
async function assertRef(Model, id, companyId, message) { if (!id) return null; const found = await Model.findOne({ _id: id, companyId, isActive: true }).lean(); if (!found) throw new ApiError(422, message); return found; }
async function listProducts(companyId, query = {}) { const filters = { companyId, isActive: true }; if (query.categoryId) filters.categoryId = query.categoryId; if (query.isService !== undefined) filters.isService = query.isService === "true"; const items = await Product.find(filters).sort({ name: 1 }).lean(); return items.map(map); }
async function createProduct(companyId, actorUserId, payload) { await assertRef(Unit, payload.unitId, companyId, "A valid active unit is required."); await assertRef(ProductCategory, payload.categoryId, companyId, "A valid active product category is required."); await assertRef(TaxRate, payload.taxId, companyId, "A valid active tax rate is required."); const product = await Product.create({ ...payload, companyId, sku: payload.sku.trim().toUpperCase(), name: payload.name.trim(), purchasePrice: Number(payload.purchasePrice || 0), sellingPrice: Number(payload.sellingPrice || 0), reorderLevel: Number(payload.reorderLevel || 0), minimumStock: Number(payload.minimumStock || 0), createdBy: actorUserId, updatedBy: actorUserId }); return map(product); }
module.exports = { list, create, update, archive, restore, listProducts, createProduct };
