const { Unit } = require("../models/Unit"); const { ProductCategory } = require("../models/ProductCategory"); const { TaxRate } = require("../models/TaxRate"); const { PaymentTerm } = require("../models/PaymentTerm"); const { Product } = require("../models/Product"); const { ContactGroup } = require("../models/ContactGroup"); const { Warehouse } = require("../models/Warehouse"); const { PriceList } = require("../models/PriceList"); const { Attachment } = require("../models/Attachment"); const { ApiError } = require("../utils/apiError");
const config = { units: { Model: Unit }, categories: { Model: ProductCategory }, "tax-rates": { Model: TaxRate }, "payment-terms": { Model: PaymentTerm }, "contact-groups": { Model: ContactGroup }, warehouses: { Model: Warehouse }, "price-lists": { Model: PriceList }, products: { Model: Product }, attachments: { Model: Attachment } };
function map(item) { const value = item.toObject ? item.toObject() : item; return { ...value, id: value._id, _id: undefined }; }
const MAX_LIMIT = 100;
function activeFilter(value) {
  if (value === "all") return undefined;
  if (value === "false") return false;
  return true;
}
function pageOptions(query) { const page = Math.max(1, Number.parseInt(query.page, 10) || 1); const limit = Math.min(MAX_LIMIT, Math.max(1, Number.parseInt(query.limit, 10) || 20)); return { page, limit }; }
async function list(resource, companyId, query = {}) { const { Model } = config[resource]; const isActive = activeFilter(query.isActive); const filter = { companyId }; if (isActive !== undefined) filter.isActive = isActive; if (query.search) filter.name = new RegExp(String(query.search).replace(/[.*+?^${}()|[\]\\]/g, "\\$&").slice(0, 100), "i"); if (query.page !== undefined || query.limit !== undefined) { const { page, limit } = pageOptions(query); const [items, total] = await Promise.all([Model.find(filter).sort({ name: 1, _id: 1 }).skip((page - 1) * limit).limit(limit).lean(), Model.countDocuments(filter)]); return { items: items.map(map), meta: { page, limit, total, totalPages: Math.ceil(total / limit), hasNextPage: page * limit < total } }; } return (await Model.find(filter).sort({ name: 1 }).lean()).map(map); }
async function get(resource, companyId, id) { const { Model } = config[resource]; const item = await Model.findOne({ _id: id, companyId }).lean(); if (!item) throw new ApiError(404, "Master record was not found."); return map(item); }
async function create(resource, companyId, actorUserId, payload) { const { Model } = config[resource]; const item = await Model.create({ ...payload, companyId, createdBy: actorUserId, updatedBy: actorUserId }); return map(item); }
async function update(resource, companyId, actorUserId, id, payload) { const { Model } = config[resource]; const item = await Model.findOne({ _id: id, companyId }); if (!item) throw new ApiError(404, "Master record was not found."); Object.assign(item, payload, { updatedBy: actorUserId }); await item.save(); return map(item); }
async function archive(resource, companyId, actorUserId, id) { const { Model } = config[resource]; const item = await Model.findOne({ _id: id, companyId }); if (!item) throw new ApiError(404, "Master record was not found."); Object.assign(item, { isActive: false, deletedAt: new Date(), deletedBy: actorUserId, updatedBy: actorUserId }); await item.save(); return map(item); }
async function restore(resource, companyId, actorUserId, id) { const { Model } = config[resource]; const item = await Model.findOne({ _id: id, companyId }); if (!item) throw new ApiError(404, "Master record was not found."); Object.assign(item, { isActive: true, deletedAt: null, deletedBy: null, updatedBy: actorUserId }); await item.save(); return map(item); }
async function assertRef(Model, id, companyId, message) { if (!id) return null; const found = await Model.findOne({ _id: id, companyId, isActive: true }).lean(); if (!found) throw new ApiError(422, message); return found; }
async function listProducts(companyId, query = {}) { const filters = { companyId }; const isActive = activeFilter(query.isActive); if (isActive !== undefined) filters.isActive = isActive; if (query.categoryId) filters.categoryId = query.categoryId; if (query.isService !== undefined) filters.isService = query.isService === "true"; if (query.search) filters.name = new RegExp(String(query.search).replace(/[.*+?^${}()|[\]\\]/g, "\\$&").slice(0, 100), "i"); if (query.page !== undefined || query.limit !== undefined) { const { page, limit } = pageOptions(query); const [items, total] = await Promise.all([Product.find(filters).sort({ name: 1, _id: 1 }).skip((page - 1) * limit).limit(limit).lean(), Product.countDocuments(filters)]); return { items: items.map(map), meta: { page, limit, total, totalPages: Math.ceil(total / limit), hasNextPage: page * limit < total } }; } const items = await Product.find(filters).sort({ name: 1 }).lean(); return items.map(map); }
async function createProduct(companyId, actorUserId, payload) { await assertRef(Unit, payload.unitId, companyId, "A valid active unit is required."); await assertRef(ProductCategory, payload.categoryId, companyId, "A valid active product category is required."); await assertRef(TaxRate, payload.taxId, companyId, "A valid active tax rate is required."); const product = await Product.create({ ...payload, companyId, sku: payload.sku.trim().toUpperCase(), name: payload.name.trim(), purchasePrice: Number(payload.purchasePrice || 0), sellingPrice: Number(payload.sellingPrice || 0), reorderLevel: Number(payload.reorderLevel || 0), minimumStock: Number(payload.minimumStock || 0), createdBy: actorUserId, updatedBy: actorUserId }); return map(product); }
async function updateProduct(companyId, actorUserId, id, payload) { if (payload.unitId !== undefined) await assertRef(Unit, payload.unitId, companyId, "A valid active unit is required."); if (payload.categoryId !== undefined) await assertRef(ProductCategory, payload.categoryId, companyId, "A valid active product category is required."); if (payload.taxId !== undefined) await assertRef(TaxRate, payload.taxId, companyId, "A valid active tax rate is required."); const normalized = { ...payload, updatedBy: actorUserId }; if (payload.sku !== undefined) normalized.sku = payload.sku.trim().toUpperCase(); if (payload.name !== undefined) normalized.name = payload.name.trim(); for (const field of ["purchasePrice", "sellingPrice", "reorderLevel", "minimumStock"]) if (payload[field] !== undefined) normalized[field] = Number(payload[field]); const product = await Product.findOneAndUpdate({ _id: id, companyId }, { $set: normalized }, { new: true, runValidators: true }); if (!product) throw new ApiError(404, "Master record was not found."); return map(product); }
module.exports = { list, get, create, update, archive, restore, listProducts, createProduct, updateProduct };
